# Generated by Django 5.2.2 on 2025-06-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Admin Amount (10%)')),
                ('owner_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Owner Amount (90%)')),
                ('is_paid_to_owner', models.BooleanField(default=False, verbose_name='Paid to Owner')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Paid Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='payments.transaction')),
            ],
        ),
    ]
