# Generated by Django 5.2.1 on 2025-05-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Wallet Balance'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('transaction_type', models.CharField(choices=[('booking', 'Booking Payment'), ('refund', 'Booking Refund'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus')], max_length=20, verbose_name='Transaction Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
