# Generated by Django 5.2.1 on 2025-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_venue_is_featured_alter_room_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('event_space', 'Event Space'), ('conference', 'Conference Center'), ('banquet', 'Banquet Hall'), ('cafe', 'Café')], default='event_space', max_length=20, verbose_name='Venue Type'),
        ),
    ]
